# hexagon formation yaml
# global goal setting
global_goal:
  swarm_central_pos: {x: 25.0, y: 0.0, z: 1.0}
  swarm_scale : 2.0
  relative_pos_0 : {x: 0.0, y: 0.0, z: 0.0}
  relative_pos_1 : {x: 1.7321, y: -1.0, z: 0.0}
  relative_pos_2 : {x: 0.0, y: -2.0, z: 0.0}
  relative_pos_3 : {x: -1.7321, y: -1.0, z: 0.0} 
  relative_pos_4 : {x: -1.7321, y: 1.0, z: 0.0}
  relative_pos_5 : {x: 0.0, y: 2.0, z: 0.0}
  relative_pos_6 : {x: 1.7321, y: 1.0, z: 0.0} 
